fix: update plugin to latest template build

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -1,59 +1,22 @@
 #!/usr/bin/env bash
 
-set \
-  -o errexit \
-  -o nounset \
-  -o pipefail
+set -euo pipefail
 
-# required environment variables
-: ${ASDF_INSTALL_VERSION?}
-: ${ASDF_DOWNLOAD_PATH?}
+current_script_path=${BASH_SOURCE[0]}
+plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
-readonly repository="particledecay/kconf"
-readonly toolname="kconf"
+# shellcheck source=./lib/utils.bash
+source "${plugin_dir}/lib/utils.bash"
 
-# rate limit support with a proper token
-CURL="curl -s"
-if [ -n "${OAUTH_TOKEN:-}" ]
-then
-  CURL="$CURL -H 'Authorization: token $OAUTH_TOKEN'"
-fi
+mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-download() {
-  local -r os=$(get_os)
-  local -r arch=$(get_arch)
-  local -r filename="${toolname}-${os}-${arch}-${ASDF_INSTALL_VERSION}.tar.gz"
-  local -r download_url="$(get_download_url $filename)"
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$(get_os)-$(get_arch)-$ASDF_INSTALL_VERSION.tar.gz"
 
-  echo "Downloading ${toolname} version ${ASDF_INSTALL_VERSION} from ${download_url}"
-  if $CURL -fsL "${download_url}" -o "${ASDF_DOWNLOAD_PATH}/${filename}"
-  then
-    echo "Successfully downloaded ${filename}"
-    exit 0
-  else
-    echo "Failed to download ${filename}"
-    exit 1
-  fi
-}
+# Download tar.gz file to the download directory
+download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-# get the OS family name
-get_os() {
-  uname | tr '[:upper:]' '[:lower:]'
-}
+#  Extract contents of tar.gz file into the download directory
+tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" "$TOOL_NAME" || fail "Could not extract $release_file"
 
-# get the cpu architecture
-get_arch() {
-  uname -m
-}
-
-# return the full URL to the download
-get_download_url() {
-  local -r filename=$1
-
-  local -r os=$(get_os)
-  local -r arch=$(get_arch)
-
-  echo "https://github.com/$repository/releases/download/v${ASDF_INSTALL_VERSION}/$filename"
-}
-
-download
+# Remove the tar.gz file since we don't need to keep it
+rm "$release_file"
