feat: add download script and standardize all scripts

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,54 +1,56 @@
 #!/usr/bin/env bash
 
 set \
-    -o errexit \
-    -o nounset \
-    -o pipefail
+  -o errexit \
+  -o nounset \
+  -o pipefail
 
 # required environment variables
 : ${ASDF_INSTALL_TYPE?}
 : ${ASDF_INSTALL_VERSION?}
 : ${ASDF_INSTALL_PATH?}
+: ${ASDF_DOWNLOAD_PATH?}
 
 readonly repository="particledecay/kconf"
 readonly toolname="kconf"
 
-# make a temporary download directory with a cleanup hook
-readonly TMP_DOWNLOAD_DIR="$(mktemp -d -t "asdf_${toolname}_XXXXXX")"
-trap 'rm -rf "${TMP_DOWNLOAD_DIR?}"' EXIT
-
 install() {
-    local -r install_type="$1"
-    local -r version="$2"
-    local -r install_path="$3"
+    local -r os=$(get_os)
+    local -r arch=$(get_arch)
+    local -r filename="${toolname}-${os}-${arch}-${ASDF_INSTALL_VERSION}.tar.gz"
+    local -r download_pkg="${ASDF_DOWNLOAD_PATH}/${filename}"
 
-    local -r bin_install_path="${install_path}/bin"
-    local -r download_url="$(get_download_url "${version}")"
-    local -r download_path="${TMP_DOWNLOAD_DIR}/$(basename "${download_url}")"
-
-    echo "Downloading ${toolname} version ${version} from ${download_url}"
-    if curl -fsL "${download_url}" -o "${download_path}"; then
-        echo "Cleaning ${toolname} previous binaries"
-        rm -rf "${bin_install_path}/${toolname}"
-
-        echo "Creating ${toolname} bin directory"
-        mkdir -p "${bin_install_path}"
-
-        extracted=
-        if [[ $download_path == *.tar.gz ]]; then
-            echo "Extracting ${toolname} tar archive"
-            tar xvf "${download_path}" -C "$bin_install_path" "$toolname" 2> /dev/null
-            [ $? -eq 0 ] && extracted=true
-        fi
-
-        if [ -z $extracted ]; then
-            echo "Error: did not properly extract ${toolname} from archive"
-            exit 1
-        fi
-    else
-        echo "Error: ${toolname} version ${version} not found" >&2
-        exit 1
+    # check if already installed
+    local -r installed=$(list_installed_versions | grep -c ${ASDF_INSTALL_VERSION})
+    if [ $installed -ne 0 ]
+    then
+      echo "Version ${ASDF_INSTALL_VERSION} of ${toolname} already installed"
+      exit 0
     fi
+
+    # download package if not already downloaded
+    if [ ! -e "$download_pkg" ]
+    then
+      ./download "${ASDF_INSTALL_VERSION}" "${ASDF_DOWNLOAD_PATH}"
+    fi
+
+    echo "Extracting ${toolname} from tar archive"
+    tar xvf "$download_pkg" -C "${ASDF_INSTALL_PATH}/bin" "$toolname" 2> /dev/null
+    if [ $? -eq 0 ]
+    then
+      echo "Successfully installed ${toolname} ${ASDF_INSTALL_VERSION}"
+      exit 0
+    else
+      echo "Failed to install ${toolname} ${ASDF_INSTALL_VERSION}"
+      exit 1
+    fi
+}
+
+list_installed_versions() {
+  for install in $(ls -d ${ASDF_INSTALL_PATH}/*/ 2>/dev/null)
+  do
+    echo "$(basename $install)"
+  done
 }
 
 get_os() {
@@ -59,11 +61,4 @@ get_arch() {
   uname -m
 }
 
-get_download_url() {
-    local -r version="$1"
-    local -r os="$(get_os)"
-    local -r arch="$(get_arch)"
-    echo "https://github.com/$repository/releases/download/v$version/${toolname}-${os}-${arch}-${version}.tar.gz"
-}
-
-install "${ASDF_INSTALL_TYPE}" "${ASDF_INSTALL_VERSION}" "${ASDF_INSTALL_PATH}"
+install
